title: SoRa's Portfolio
name: SoRa Lee
email: 2sora71@gmail.com
description:
  Web Publisher SoRa Lee


baseurl: ""
url: "https://sora.github.io"


# profile 이미지
profile_image: images/me_256x256.png


# SNS 아이디
facebook_id: 
instagram_id: 


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #19aad1
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_1.jpg
  title: 안녕하세요! <br>이소라입니다.</br>
  position: absolute
  transform: translate( -50%, -50% )
  left: 0px
  bottom: 500px


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_3.jpg
  title: I am<br>Web Publisher
  subtitle: >- 
    천천히<br>
    그리고 꾸준히<br>
    끊임없이 노력하는<br>
    이소라입니다.
  position: absolute
  transform: translate( -50%, -50% )
  left: 20px
  bottom: 550px

# About
about_meta: About Me
about_header: >- 
  "소통하는 퍼블리셔"
about_introduce: >-
  "안녕하세요. 6년차 퍼블리셔 이소라입니다."
about_content: >-
  TV와 라디오가 좋아 지원했던 고등학교시절 방송반,<br>
  그 취향 그대로 진학한 방송영상학과<br>
  여러 파트 중에도 <strong>"편집"</strong>이 좋아 편집만 했던 학생이었습니다.<br>
  방송업무 특성이 맞지 않는 것 같아 다른 일을 알아보다가 알게 된 것이 퍼블리셔였습니다.<br>
  <strong>"사이트를 편집"</strong>하여 만든다는 것에 흥미를 느껴 전향하여 퍼블리셔로 일하고 있습니다.
about_services: # 형식에 맞추어 항목 추가
- icon: icon-monitor
  name: PC Web<br>
- icon: icon-phone3
  name: Mobile
- icon: icon-device-tablet
  name: Tablet
- icon: icon-code
  name: HTML5, CSS3, JS
about_box_content: >-
  "하면 된다"<br><br>
  무슨 일이라도 일단 도전하면 된다는 저희 집 가훈입니다.<br>
  아버지의 말씀을 따라 도전정신을 갖고 임하는 태도를 갖게 되었습니다.

about_box_content_color: rgb(255,255,255)

#about_box_button:
  #link: #
  #name: sample


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 제가 사용할 수 있는 스킬입니다.
tech_content: 
tech_list: # 형식에 맞추어 항목 추가
- name: HTML5
  color: color-1
  animation: fadeInRight
  percent: 90
  mark: 90
  content: 매번 마크업 하며 많이 사용하는 만큼 무엇보다 손에 익숙합니다. 그래서 빠르게 작업할 수 있습니다.
- name: CSS3
  color: color-2
  animation: fadeInRight
  percent: 80
  mark: 80
  content: 많이 알고 있는 것 같지만, 하다보면 또 어려운 점이 생기는 것 같습니다. 부족한 부분은 공부하여 채우려고 하고 있습니다.
- name: JavaScript
  color: color-3
  animation: fadeInRight
  percent: 50
  mark: 50
  content: 동적인 화면구현을 위해 계속해서 공부중입니다.
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 50
  mark: 50
  content: git을 이용하여 소스 관리가 가능합니다.
- name: Vue.js
  color: color-5
  animation: fadeInRight
  percent: 30
  mark: 30
  content: Vue 환경에서 마크업과 간단한 스크립트를 사용할 수 있습니다.
- name: SCSS
  color: color-6
  animation: fadeInRight
  percent: 40
  mark: 40
  content: 템플릿화 하여 소스관리가 가능합니다.
tech_desc: Vue.js 환경에서 작업이 가능해진 지금은, React 환경에서도 작업 할 수 있도록 공부할 것입니다.


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: 팀 프로젝트
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: #
project_team_name: Growv
project_team: # 형식에 맞추어 항목 추가
- background_url: images/growv_web_1.jpg
  animation: fadeInRight
  name: SuperV Web Site - 70%
  description: 슈퍼브이 홈페이지입니다. 외주 작업으로 기본 틀이 제작되었지만, 이후 유지보수를 하며 코드를 대량 수정하였습니다.
  detail_url: https://2sora.github.io/2sora_work.github.io/growv_web_1/main.html
  readmore_url: https://github.com/2SoRa/2sora_work.github.io/tree/main/growv_web_1/
- background_url: images/growv_tablet_1.jpg
  animation: fadeInRight
  name: SuperV tablet WebView - 100%
  description: 슈퍼브이 태블릿 내의 웹뷰 화면중 일부입니다. Vue3 환경에서 작업되었으며, 태블릿 내의 웹뷰 화면은 모두 마크업 했습니다.
  detail_url: https://2sora.github.io/2sora_work.github.io/growv_tablet_1/public/schedule.html
  readmore_url: https://github.com/2SoRa/2sora_work.github.io/tree/main/growv_tablet_1/src/views/launcher/schedule/comp/schedule.vue
# project_team_name: e-future
# project_team: # 형식에 맞추어 항목 추가
# - background_url: images/project1.jpg
#   animation: fadeInLeft
#   name: e-Library(기본) - 선생님
#   description: e-future의 Online Library입니다. 전체적으로 마크업 작업을 하였고, 필요에 따라 부분적으로 디자인 한 것도 있습니다. 이 사이트는 국내 기관(ex. 강원도 교육청)과 해외 수출용으로 만들어진 사이트입니다. 
#   detail_url: https://2sora.github.io/2sora_work.github.io/library1/web/teacher/main/main.html
#   readmore_url: https://github.com/2SoRa/2sora_work.github.io/tree/main/library1/web/teacher
# - background_url: images/project2.jpg
#   animation: fadeInLeft
#   name: e-Library(기본) - 학생
#   description: e-future의 Online Library입니다. 전체적으로 마크업 작업을 하였고, 필요에 따라 부분적으로 디자인 한 것도 있습니다. 이 사이트는 국내 기관(ex. 강원도 교육청)과 해외 수출용으로 만들어진 사이트입니다.
#   detail_url: https://2sora.github.io/2sora_work.github.io/library1/web/student/main/main.html
#   readmore_url: https://github.com/2SoRa/2sora_work.github.io/tree/main/library1/web/student
# - background_url: images/project3.jpg
#   animation: fadeInLeft
#   name: e-Library(공부방) - 선생님
#   description: e-future의 Online Library입니다. 전체적으로 마크업 작업을 하였고, 필요에 따라 부분적으로 디자인 한 것도 있습니다. 이 사이트는 국내 공부방용(소규모 결제)으로 만들어진 사이트입니다.
#   detail_url: https://2sora.github.io/2sora_work.github.io/library2/web/teacher/main/main.html
#   readmore_url: https://github.com/2SoRa/2sora_work.github.io/tree/main/library2/web/teacher
# - background_url: images/project4.jpg
#   animation: fadeInLeft
#   name: e-Library(공부방) - 학생
#   description: e-future의 Online Library입니다. 전체적으로 마크업 작업을 하였고, 필요에 따라 부분적으로 디자인 한 것도 있습니다. 이 사이트는 국내 공부방용(소규모 결제)으로 만들어진 사이트입니다.
#   detail_url: https://2sora.github.io/2sora_work.github.io/library2/web/student/main/main.html
#   readmore_url: https://github.com/2SoRa/2sora_work.github.io/tree/main/library2/web/student
# - background_url: images/project5.jpg
#   animation: fadeInLeft
#   name: e-Library(기본/모바일) - 학생
#   description: e-future의 Online Library입니다. 전체적으로 마크업 작업을 하였고, 다양한 모바일 기기에서 최적화 되도록 작업하였습니다. **모바일 화면에서 새로고침 후 확인부탁드립니다.**
#   detail_url: https://2sora.github.io/2sora_work.github.io/library1/mobile/production/main/profile.html
#   readmore_url: https://github.com/2SoRa/2sora_work.github.io/tree/main/library1/mobile/production/main/


# Experience
exp_meta: What have I achieved?
exp_header: 저의 역량은 이렇습니다!
exp_content: 부족하다 생각하실 수 있지만 저는 이런 퍼블리셔랍니다:)
exp_services: # 형식에 맞추어 항목 추가
- name: 커뮤니케이션
  color: color-1
  icon: icon-speech-bubble
  content: 개발자, 디자이너와의 커뮤니케이션 능력이 뛰어납니다.
- name: 프로젝트
  color: color-2
  icon: icon-fire2
  content: 제가 맡은 일은 빠르게 처리할 수 있는 빠른 손을 가졌습니다.
- name: 기술습득
  color: color-3
  icon: icon-eye
  content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해  끊임없이 공부하고 즐거운 마음으로 배웁니다.


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: (주)그로비교육
  date: 2022.04 ~ 2024.04
  content: 유아 학습 태블릿 및 컨텐츠
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
- name: 쌤투쌤
  date: 2021.11 ~ 2021.12
  content: 교사와 학부모를 위한 교육자료 공유 플랫폼
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft
- name: (주)이퓨쳐
  date: 2018.03 ~ 2021.11
  content: 온라인 영어 교육 전문업체. 유아동 영어 교재 출판사
  color: color-3
  icon: icon-pen2
  animation: fadeInLeft


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: Smart Web Design & Contents Develop
  subtitle: 스마트 웹 디자인 & 컨텐츠 개발 / 이젠컴퓨터학원
  date: 2017.06 ~ 2017.12
  content: 웹 퍼블리셔 양성 과정 수료
- title: KANGWON UNIVERSITY
  subtitle: 강원대학교 
  date: 2012.03 - 2016.02
  content: 강원대학교 방송영상학과 졸업
- title: DONGNAM HIGH SCHOOL
  subtitle: 동남고등학교
  date: 2009.03 - 2012.02
  content: 포천 동남고등학교 졸업

# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: 궁금한게 있으시면 연락주세요
  icon: icon-globe-outline
- title: 경기도 포천시
  icon: icon-map
- title: Kakao - Superman701
  icon: icon-phone
- title: e-mail
  icon: icon-layers2
  url: 2sora71@gmail.com
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
